### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by click20100** [ChristinesMan/ChristineAI#2]
Hello,

I also have a TPE doll... Paige from the WM doll company. How did you install the sensors without damaging the doll?

I am not familiar with the python language nor with the raspberry.
But your project interests me a lot.
You could give me the basic explanations for installing the program on the Pi and the list of components to buy for the construction.
A small wiring diagram would be appreciated.

Thanks a lot in advance,
claude

**Comment by ChristinesMan** [comment]
Hello! I guess after a while of poking her I've just become comfortable with causing damage. :)  It's been a long road of learning. 

I will see what I can provide. The idea of someone else building something similar is intriguing. In my biased opinion, my doll AI is better than anything else I see out there. The disadvantage is mainly durability, because it's cobbled together and things tend to break on a regular basis. Inside a doll is a difficult environment to build in. 

I would like to make diagrams, but every time I try and make something like that I'm not sure how to begin. But you can have the photos that I have taken every step of the way. And I'll make a parts list. I'll gather that up and get back to you.

**Comment by ChristinesMan** [comment]
Ok, I''m done for now. Added some more info. Thanks for the motivation. 

If you're serious about really building and would like to get the build pics and videos, please message me on Doll Forum at "Christines Man" and I'll figure out the best way to provide. I've just been hoarding them.
